file_spec:
  delimiter: ","
  quoted: True
  skip_header: True

tables:
  sf_donations: "/var/salesforce-fetcher/contact_donor_count/{date}/output.csv"
  sf_foundation_signups: "/var/salesforce-fetcher/foundation_signups/{date}/output.csv"
  sf_donation_count: "/var/salesforce-fetcher/donation_record_count/{date}/output.csv"
  sf_copyright_petition: "/var/salesforce-fetcher/petition_signups/{date}/output.csv"
